---
title: "ESM232 Assignment 8: Evaluating Models"
author: "Pat Byrne, Kat Leigh, Ruoyu Wang"
date: "5/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(purrr)
library(lubridate)
```

### 1. Code metric as a function

Our metric: estimated minimal and maximal flow must both have a Pearson’s Correlation Coefficient greater than 0.6, but the closer to 1, the better.

```{r func}
# call out function "perform_metric"
source('kat_pat_ruoyu_perform_metric.R')
```

### 2. Apply to the streamflow data provided in sagerm.txt (multiple model results)

```{r data}
# read observation data
sager <- read.table("sager.txt", header=T)

# add date from the existing columns of day, month, year
sager <- sager %>% 
  mutate(date=make_date(year=year, month=month, day=day))

# read in simulation outputs
msage = read.table("sagerm.txt", header=T)

# combine the simulation outputs with date and acutal observation data in sager.txt
msage$date = sager$date
msage$month = sager$month
msage$year = sager$year
msage$day = sager$day
msage$wy = sager$wy
msage$obs = sager$obs
```

```{r clean.data}
# turn all the columns of different outputs into a single column identified by "run"
msagel = msage %>% 
  gather(key="run",
         value="streamflow", 
         -date, -month, -day, 
         -year, -wy, -obs)
```


```{r apply}
# apply the perform_metric function to our data, the grouping variable is year
res = msage %>% 
  select(-date, -month, -day, -year, -wy, -obs) %>%
  map_dfr(~perform_metric(m=.x, 
                          o=msage$obs, 
                          month = msage$month, 
                          day = msage$day,
                          year=msage$year, 
                          wy=msage$wy,
                          grouping=msage$year))


# crate an ID that tracks each model output
simnames = names(msage %>% 
  select(-date, -month, -day,-year,-wy, -obs))

results = cbind.data.frame(simnames=simnames, res)

# Make results long format
resultsl = results %>% 
  gather(key="metric",value="value", -simnames) 
```

### 3.  Find the simulation that gives the best performance 

```{r best}
# find the best model run (highest average correlation, and both coefficients are larger than 0.6)

bestdf <- results %>% 
  filter(annual_min_cor > 0.6,
         annual_max_cor > 0.6) %>%  
  mutate(
    ave_cor = (annual_min_cor+annual_max_cor)/2
  ) %>% 
  arrange(-ave_cor)

print(as.character(bestdf$simnames[1]))
```


### 4. Create a boxplot of our metric applied to sagerm.txt

```{r boxplot, fig.width=7, fig.height=4}
# graph range of performance measures
ggplot(resultsl, aes(metric, value))+
  geom_boxplot()+
  facet_wrap(~metric, scales="free")+
  labs(x='Performance Metric Correlated Variable',
       y='Pearson Correlation Coefficient',
       title = 'Model Performance: Correlation between Simulated and Observed Values')+
  theme_bw()+
  theme(axis.text.x = element_blank())
```
